export const ActionTypes = {
  SET_EMAILS: "SET_EMAILS",
  SELECTED_EMAIL: "SELECTED_EMAIL",
  MARK_FAVORITE: "MARK_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  MARK_READ: "MARK_READ",
  SET_FILTER: "SET_FILTER",
};
